version: "3.7"
services:
  backend:
    image: zenith110/pubsub-backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - 2053:80
  frontend:
    image: zenith110/pubsub-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    ports:
      - 80:80
    depends_on: 
    - backend
    links: 
    - backend
    
    
  