version: "3.7"
services:
  backend:
    build: ./backend/v1
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - 5000:80
  frontend:
    build: ./frontend/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true 
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5001:3000
    depends_on: 
    - backend
    links: 
    - backend
    
    
  