version: "3.9"
services:
  backend:
    build: ./backend/v1
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - 5000:80
  frontend:
    build: ./frontend/
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    ports:
      - 80:80
    depends_on: 
    - backend
    
    
  